import HautevilleHouse.ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean.ReactionKinetics
import HautevilleHouse.ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean.MichaelisMentenKinetics
import HautevilleHouse.ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean.ThermodynamicConsistency
import HautevilleHouse.ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean.MassTransfer
import HautevilleHouse.ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean.BioreactorDesign

namespace HautevilleHouse
namespace ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean

structure AdmissibleClass where
  object : ReactionKineticsPackage × MichaelisMentenPackage × ThermodynamicConsistencyPackage × MassTransferPackage × BioreactorDesignPackage
  endpointSatisfied : Prop
  remainderRecorded : Prop
  gateWitness : endpointSatisfied ∨ remainderRecorded

end ChemicalEngineeringBiochemicalEngineeringTheoremCanonicalLaneLean
end HautevilleHouse